- target: "girl"
  positive: "old, wrinkled face, grey hair"
  unconditional: ""
  neutral: "girl"
  action: "enhance"
  guidance_scale: 3.0
  resolution: 512
  batch_size: 2

- target: "boy"
  positive: "old, wrinkled face, grey hair"
  unconditional: ""
  neutral: "boy"
  action: "enhance"
  guidance_scale: 3.0
  resolution: 512
  batch_size: 2
